CREATE DATABASE IPL;

use IPL;

CREATE TABLE Players(
    	PlayerID CHARACTER(5) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL, 
	Nationality  VARCHAR(50) NOT NULL,
	DoB DATE NOT NULL,
	Role  VARCHAR(50),
	StrikeRate DECIMAL(5,2),
	BowlingStyle  VARCHAR(50),
	BattingStyle  VARCHAR(50)
);

CREATE TABLE TitleSponsor(
	CompanyName VARCHAR(50) PRIMARY KEY,
	BusinessDomain VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL	
);

CREATE TABLE TeamOwner(
	CompanyName VARCHAR(50) PRIMARY KEY,
	BusinessDomain VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL
);

CREATE TABLE HeadCoach(
	CoachID CHARACTER(5) PRIMARY KEY,
	CoachName VARCHAR(50) NOT NULL,
	Years_of_Experience SMALLINT,
	DoB DATE NOT NULL,
	Country VARCHAR(50) NOT NULL
);

CREATE TABLE Teams(
	TeamID VARCHAR(5) PRIMARY KEY,
	TeamName VARCHAR(50) UNIQUE NOT NULL,
	CompanyName VARCHAR(50) ,
	FOREIGN KEY(CompanyName) REFERENCES TeamOwner(CompanyName)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Umpire(
	UmpireID CHARACTER(5) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	YearsOfExperience SMALLINT,
	Country VARCHAR(50) NOT NULL	
);

CREATE TABLE Stadium(
	StadiumName VARCHAR(50),
	City VARCHAR(50),
	Country VARCHAR(50) NOT NULL,
	Capacity INT,
	RentAmount BIGINT,
	PRIMARY KEY (StadiumName, City)
);

CREATE TABLE Match_1 (
    MatchID CHARACTER(7) PRIMARY KEY,
    MatchType VARCHAR(10) NOT NULL,
    Date DATE NOT NULL,
    StadiumName VARCHAR(50) NOT NULL,
    City VARCHAR(50) NOT NULL,
    PlayerID CHARACTER(5) NOT NULL,
    FOREIGN KEY (StadiumName, City) REFERENCES Stadium(StadiumName, City)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE UmpiredBy(
	MatchID CHARACTER(7),
	UmpireID CHARACTER(5),
	PRIMARY KEY (MatchID, UmpireID),
	FOREIGN KEY (MatchID) REFERENCES Match_1(MatchID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (UmpireID) REFERENCES Umpire(UmpireID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IPL(
	Year SMALLINT PRIMARY KEY, 
	CompanyName VARCHAR(50) NOT NULL,
	PlayerID CHARACTER(5) NOT NULL,
	TeamID VARCHAR(5) NOT NULL,
	FOREIGN KEY (TeamID) REFERENCES Teams(TeamID) 
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CompanyName) REFERENCES TitleSponsor(CompanyName)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TeamDetails(
	TeamID VARCHAR(5),
	Year SMALLINT,
	PlayerID CHARACTER(5) NOT NULL,
    	CoachID CHARACTER(5) NOT NULL,
	CompanyName VARCHAR(50) NOT NULL,
	SponsorAmount BIGINT NOT NULL,	
	PRIMARY KEY (TeamID, Year),
	FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CoachID) REFERENCES HeadCoach(CoachID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CompanyName) REFERENCES TitleSponsor(CompanyName)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (TeamID) REFERENCES Teams(TeamID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Year) REFERENCES IPL(Year) 
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE YearwisePlayerDetails(
	PlayerID CHARACTER(5),
	Year SMALLINT, 
	TeamID VARCHAR(5) NOT NULL,
	TotalWickets INT,
	TotalRuns INT,
	MaximumWickets INT,
	MaximumWicketsRuns INT,
	MaximumRuns INT,
	PlayerPrice BIGINT,
	Out_NotOut BOOLEAN,
	PRIMARY KEY(PlayerID,Year),
	FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (TeamID, Year) REFERENCES TeamDetails(TeamID, Year)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Played(
	MatchID CHARACTER(7),
	TeamID VARCHAR(5),
	TeamRuns INT NOT NULL,
	4s INT NOT NULL,
	6s INT NOT NULL,
	Wickets INT NOT NULL,
	Winner CHARACTER(1) NOT NULL, 
	PRIMARY KEY(MatchID,TeamID),
	FOREIGN KEY (TeamID) REFERENCES Teams(TeamID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (MatchID) REFERENCES Match_1(MatchID)
		ON DELETE CASCADE ON UPDATE CASCADE);

